### ISSUE TITLE
Moo conversion / Type checking broke Data::HAL

### ISSUE THREAD

**Issue by castaway** [kjetilk/URI-NamespaceMap#9]
Data::HAL tries to stuff Data::HAL::URI objects into add_mapping, however the assert_coerce to Namespace doesn't like that and rejects it. - I presume Data::HAL worked ok pre that change as it has a pile of PASSes on cpantesters.

My gut instinct is to remove the assert_coerce, tho that makes the test that passes a plain string to it fail..

**Comment by kjetilk** [comment]
Thanks for the report! I should at lease ping tobyink about this before making any changes, that's largely his work.

**Comment by kjetilk** [comment]
In @tobyink's absence lets see if we can understand it sufficiently, I've got a few minutes right now... :-)

So, the offending line is 
https://github.com/kjetilk/URI-NamespaceMap/blob/d5b181f005eafe6733aac61a4bc4becd011c74f7/lib/URI/NamespaceMap.pm#L112

I'd like to be able to pass a plain string, but perhaps there are other ways to do that? 

Could adding new coercions somewhere fix the problem?

**Comment by kjetilk** [comment]
Seems like Data::HAL has a workaround for this now? Is it still something that should be fixed in URI::NamespaceMap?

**Comment by gregoa** [comment]
After some searching I found https://github.com/sipwise/data-hal with https://github.com/sipwise/data-hal/commit/85538c754b0274251319597d23d04ca135e7f463 and https://github.com/sipwise/data-hal/commit/ac5f0bf5f72997fa3cbd84820e8aeb011e76bc3d . I guess that's what you are referring to?
In any case, with these changes all looks fine to me indeed.

Cheers,
gregor

**Comment by kjetilk** [comment]
Yeah, those are the commits I was referring to. So, are people fine with the current situation?

**Comment by castaway** [comment]
Had forgotten this existed.. kwa just pointed me at it.. now, wtf was I using Data::HAL for.. ?

**Comment by kjetilk** [comment]
Great that you're looking at it, @castaway ! I have been preparing new releases since Debian is freezing soon, if you figure something out, we could get it in! :-)

**Comment by kjetilk** [comment]
I'm adding more coercion in #16 , so if there others, then patches are welcome. :-)

**Comment by castaway** [comment]
uff blast from the past.. erm.. having looked + found what I used it for (tho not currently running anywhere).. I'd say, just ensure Data::HAL tests work? Currently , they dont: http://www.cpantesters.org/cpan/report/e42405f8-f5d1-11e9-896f-6a9ae83b1713

I can go check stuff out + run if thats useful? I seem to be doing CPAN catch ups this week too..

**Comment by kjetilk** [comment]
Great stuff, @castaway ! With my slowly increasing understanding if the typing stuff, I made a quick PR, #17 . Could you please check if that fixes the problem?

**Comment by kjetilk** [comment]
I have released https://metacpan.org/release/KJETILK/URI-NamespaceMap-1.09_03 which hopefully fixes the problem.

**Comment by castaway** [comment]
Hmm.. soo.. the Data::HAL on CPAN still fails.. now its complaining: Not a valid IRI? https://example.com/apidocs/ns/{rel} - they're templates, I dunno if that's supposed to work?

The one in the linked sipwise repo passes fine... so I guess need to poke that person into uploading to CPAN? (looks like they've been deploying to debian, bypassing cpan... )

**Comment by castaway** [comment]
.. have submitted an issue on the repo asking for a CPAN update.

**Comment by kjetilk** [comment]
Hmmm, interesting, so, if a Data::HAL::URI of the form https://example.com/apidocs/ns/{rel} expects to be a namespacemap of `rel => https://example.com/apidocs/ns/` that's a different coercion, but I could certainly include that
